### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by Chitkaran** [Fox520/DigiComo#1]
Hi, I tried to execute but received the following error

`ModuleNotFoundError: No module named 'kivymd.app'

I believe some file is missing while uploading ?

**Comment by Fox520** [comment]
Can you try this: pip install git+https://github.com/HeaTTheatR/KivyMD.git@0.102.0

**Comment by Fox520** [comment]
Or download [KivyMD zip](https://github.com/HeaTTheatR/KivyMD/archive/0.102.0.zip)
Extract, move into the directory then do ```python setup.py install```

**Comment by Chitkaran** [comment]
I guess the code that you've supplied is looking for `MDApp under kivymd.app` which doesn't exist in the kivymd directory. Do you have the file separately on your machine ?

**Comment by Fox520** [comment]
MDApp does exist (https://github.com/HeaTTheatR/KivyMD/blob/master/kivymd/app.py#L17). It could be that the version downloaded ```pip install kivymd``` does not include MDApp.

> Do you have the file separately on your machine ?

Nope.

**Comment by Chitkaran** [comment]
All Sorted! thanks for the assistance buddy.. cheers
